### ISSUE TITLE
Link should go to netlify not herokuapp?

### ISSUE THREAD

**Issue by stefek99** [PolymathNetwork/polymath-offchain#4]
![image](https://user-images.githubusercontent.com/249703/40178682-1e42ab80-59da-11e8-9988-1216d0f9c435.png)

- https://polymath-offchain.herokuapp.com/dashboard/HACK
- https://polymath-issuer.netlify.com/dashboard/HACK

Config is here:
https://github.com/PolymathNetwork/polymath-offchain/blob/2b97b5adda1b6b943d50b7d38a4f32e908bd7e02/lib/config.js

**Comment by sajclarke** [comment]
Thanks for raising this issue. Will be fixed shortly.

**Comment by stefek99** [comment]
While getting ready for the interview also that: https://www.reddit.com/r/PolymathNetwork/comments/8k43sh/scam_warning_if_something_is_too_good_to_be_true/

:)
